/**
 * Where each template's thumbnail window starts, in card pixels at 390 wide.
 *
 * Generated by measuring every template at exactly the geometry the thumbnail
 * renders at — 390 wide by 4800 tall, the SRC_W and RENDER_H in
 * thumb-geometry.ts. Re-measure whenever either of those changes: six of these
 * pages size themselves off the viewport, so their content moves when the
 * render height does.
 *
 * One rule produces all of them:
 *
 *   - If the card fits inside one 624px window, the window is anchored to
 *     the *end* of the content, sitting 24px under the last text or link. A
 *     card shorter than the window otherwise leaves half a tile of blank page
 *     underneath it.
 *   - If the card is taller than one window, end-anchoring would show the tail
 *     of a gallery and no face, so the window is anchored to the identity
 *     block instead — 16px above the avatar, which is also what keeps
 *     the top edge from slicing someone in half.
 *   - If the content ends past 4800, no offset can reach it and the frame
 *     starts at the top.
 *
 * That last case applies to dock alone, and it is not a rounding problem. Six
 * templates size themselves off the viewport, and dock is the one that does it
 * 1:1: its content bottom is always renderHeight + 402, because the docked bar
 * sits at the end of a min-h-screen block with a 402px cover stacked above it.
 * It outruns any height you pick, so raising RENDER_H will never bring it into
 * frame. Framed from the top, permanently — which shows its full-bleed cover,
 * the thing the template is actually about.
 *
 * Two measurement traps worth keeping, both of which produced offsets that
 * looked reasonable as numbers and were plainly wrong on screen:
 *
 *   - The "save to contacts" bar is position:fixed and rides the viewport
 *     bottom on all 36. Counted as content, it makes every card look like it
 *     ends at the bottom of the iframe.
 *   - The identity block cannot be found geometrically. The avatar and the
 *     gallery scenes are both square-ish inline SVG, so "the first square
 *     image" lands on a photo halfway down a gallery. It is found by matching
 *     the persona's name text, and by the avatar's own viewBox (400x520,
 *     against 400x400 for the scenes). reel additionally keeps its name in a
 *     sticky header — sticky is excluded when asking where content ends, but
 *     must be included when asking where the identity is.
 */
export const THUMB_TOP: Record<string, number> = {
  agency: 245,
  app: 40,
  aurora: 501,
  badge: 507,
  bold: 484,
  booking: 108,
  case: 497,
  clinic: 488,
  coach: 518,
  contactsheet: 452,
  dock: 0,
  editorial: 534,
  filmstrip: 1807,
  flare: 490,
  frames: 460,
  glass: 98,
  grid: 460,
  journal: 497,
  launch: 577,
  lookbook: 3557,
  masonry: 452,
  menu: 460,
  minimal: 500,
  mono: 460,
  mosaic: 452,
  neon: 486,
  orbit: 500,
  pitch: 843,
  poster: 295,
  quote: 536,
  reel: 416,
  reply: 468,
  showcase: 2590,
  split: 468,
  stack: 560,
  sticker: 496,
  studio: 416,
  summit: 485,
  tape: 477,
  tiles: 468,
  waitlist: 520,
  wellness: 501,
};

/** Templates added without a measured frame start at the top, as before. */
export function thumbTop(template: string): number {
  return THUMB_TOP[template] ?? 0;
}
