-- =====================================================================
-- Card inventory + Review Cards.
--
-- Part A extends nfc_cards (the physical card table, already the thing
-- /api/nfc/<card_url> resolves) instead of adding a second card model:
--   * serial        -> the printed "SC-000001" number, in creation order
--   * status        -> in_stock / active / suspended / retired
--   * nickname, location, batch_id, assigned_at, updated_at
--   * nfc_card_batches     -> real batch records (old free-text `batch` kept)
--   * nfc_card_events      -> assignment/status audit trail, written by a
--                             trigger so no code path can skip it
--   * resolve_nfc_card()   -> also returns status
--   * nfc_card_tap_stats() -> per-card tap totals for the inventory
--
-- Part B adds the Review Card experience on top of existing pieces:
--   * card_profiles.review_config -> the template's settings
--   * card_taps event types       -> rating / review_click / feedback_open /
--                                    feedback_submit (rating value in `target`)
--   * review_feedback             -> what customers write; owners read it,
--                                    nobody inserts except submit_review_feedback()
--
-- Nothing is dropped or renamed. Existing card codes (card_url) are
-- untouched, so every tag already written keeps working.
-- =====================================================================

-- ------------------------------------------------------------ A1 batches
CREATE TABLE IF NOT EXISTS public.nfc_card_batches (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL CHECK (char_length(name) BETWEEN 1 AND 120),
  product_type TEXT CHECK (product_type IS NULL OR char_length(product_type) <= 120),
  quantity INTEGER NOT NULL CHECK (quantity BETWEEN 1 AND 1000),
  created_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.nfc_card_batches ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Admins can manage card batches." ON public.nfc_card_batches;
CREATE POLICY "Admins can manage card batches."
  ON public.nfc_card_batches FOR ALL
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

-- ------------------------------------------------------ A2 card columns
ALTER TABLE public.nfc_cards
  ADD COLUMN IF NOT EXISTS serial BIGINT,
  ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'in_stock',
  ADD COLUMN IF NOT EXISTS nickname TEXT,
  ADD COLUMN IF NOT EXISTS location TEXT,
  ADD COLUMN IF NOT EXISTS batch_id UUID REFERENCES public.nfc_card_batches(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS assigned_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

-- Existing cards numbered in the order they were issued.
WITH ordered AS (
  SELECT id, row_number() OVER (ORDER BY created_at, id) AS rn
  FROM public.nfc_cards
)
UPDATE public.nfc_cards n
SET serial = o.rn
FROM ordered o
WHERE n.id = o.id AND n.serial IS NULL;

-- New cards continue the sequence from the highest existing number.
DO $$
DECLARE next_serial BIGINT;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'nfc_cards'
      AND column_name = 'serial' AND is_identity = 'YES'
  ) THEN
    SELECT COALESCE(MAX(serial), 0) + 1 INTO next_serial FROM public.nfc_cards;
    ALTER TABLE public.nfc_cards ALTER COLUMN serial SET NOT NULL;
    EXECUTE format(
      'ALTER TABLE public.nfc_cards ALTER COLUMN serial ADD GENERATED BY DEFAULT AS IDENTITY (START WITH %s)',
      next_serial
    );
  END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS nfc_cards_serial_key ON public.nfc_cards(serial);

-- card_url was declared UNIQUE in schema.sql; make sure that survived.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_index i
    JOIN pg_attribute a ON a.attrelid = i.indrelid AND a.attnum = ANY (i.indkey)
    WHERE i.indrelid = 'public.nfc_cards'::regclass
      AND i.indisunique AND i.indnatts = 1 AND a.attname = 'card_url'
  ) THEN
    CREATE UNIQUE INDEX nfc_cards_card_url_key ON public.nfc_cards(card_url);
  END IF;
END $$;

ALTER TABLE public.nfc_cards DROP CONSTRAINT IF EXISTS nfc_cards_status_check;
ALTER TABLE public.nfc_cards
  ADD CONSTRAINT nfc_cards_status_check
  CHECK (status IN ('in_stock', 'active', 'suspended', 'retired'));

ALTER TABLE public.nfc_cards DROP CONSTRAINT IF EXISTS nfc_cards_text_lengths;
ALTER TABLE public.nfc_cards
  ADD CONSTRAINT nfc_cards_text_lengths
  CHECK (
    (nickname IS NULL OR char_length(nickname) <= 80)
    AND (location IS NULL OR char_length(location) <= 120)
  );

-- Every card that already points at someone is live today.
UPDATE public.nfc_cards SET status = 'active'
WHERE card_profile_id IS NOT NULL AND status = 'in_stock';

CREATE INDEX IF NOT EXISTS nfc_cards_status_idx ON public.nfc_cards(status);
CREATE INDEX IF NOT EXISTS nfc_cards_batch_id_idx ON public.nfc_cards(batch_id);
CREATE INDEX IF NOT EXISTS nfc_cards_card_profile_id_idx ON public.nfc_cards(card_profile_id);
CREATE INDEX IF NOT EXISTS nfc_cards_created_at_idx ON public.nfc_cards(created_at DESC);

-- ------------------------------------------- A3 keep status consistent
-- Assigning a card makes it live, unassigning puts it back in stock, and
-- user_id always follows the profile. Enforced here so the old admin
-- actions and the new ones can never disagree.
CREATE OR REPLACE FUNCTION public.nfc_cards_before_write()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  NEW.updated_at := now();

  IF TG_OP = 'INSERT' OR NEW.card_profile_id IS DISTINCT FROM OLD.card_profile_id THEN
    IF NEW.card_profile_id IS NULL THEN
      NEW.user_id := NULL;
      NEW.assigned_at := NULL;
      IF NEW.status = 'active' THEN NEW.status := 'in_stock'; END IF;
    ELSE
      SELECT user_id INTO NEW.user_id FROM public.card_profiles WHERE id = NEW.card_profile_id;
      NEW.assigned_at := now();
      IF NEW.status = 'in_stock' THEN NEW.status := 'active'; END IF;
    END IF;
  END IF;

  IF NEW.status = 'active' AND NEW.card_profile_id IS NULL THEN
    NEW.status := 'in_stock';
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS nfc_cards_before_write ON public.nfc_cards;
CREATE TRIGGER nfc_cards_before_write
  BEFORE INSERT OR UPDATE ON public.nfc_cards
  FOR EACH ROW EXECUTE FUNCTION public.nfc_cards_before_write();

-- --------------------------------------------------- A4 audit history
-- Usernames are snapshotted so history still reads correctly after a
-- profile is renamed or deleted. nfc_card_id goes null if the card itself is
-- deleted; serial and code are kept alongside for that case.
CREATE TABLE IF NOT EXISTS public.nfc_card_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  nfc_card_id UUID REFERENCES public.nfc_cards(id) ON DELETE SET NULL,
  card_serial BIGINT,
  card_code TEXT,
  action TEXT NOT NULL CHECK (action IN (
    'created', 'assigned', 'reassigned', 'unassigned',
    'status_changed', 'details_changed', 'deleted'
  )),
  from_profile_id UUID,
  to_profile_id UUID,
  from_username TEXT,
  to_username TEXT,
  from_status TEXT,
  to_status TEXT,
  details JSONB,
  actor_id UUID,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS nfc_card_events_card_idx
  ON public.nfc_card_events(nfc_card_id, created_at DESC);

ALTER TABLE public.nfc_card_events ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Admins can read card history." ON public.nfc_card_events;
CREATE POLICY "Admins can read card history."
  ON public.nfc_card_events FOR SELECT
  USING (public.is_admin());

CREATE OR REPLACE FUNCTION public.log_nfc_card_event()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  actor UUID := auth.uid();
  from_name TEXT;
  to_name TEXT;
BEGIN
  IF TG_OP = 'INSERT' THEN
    SELECT username INTO to_name FROM public.card_profiles WHERE id = NEW.card_profile_id;
    INSERT INTO public.nfc_card_events
      (nfc_card_id, card_serial, card_code, action, to_profile_id, to_username, to_status, details, actor_id)
    VALUES
      (NEW.id, NEW.serial, NEW.card_url, 'created', NEW.card_profile_id, to_name, NEW.status,
       jsonb_build_object('batch_id', NEW.batch_id, 'nickname', NEW.nickname, 'location', NEW.location),
       actor);
    RETURN NEW;
  END IF;

  IF TG_OP = 'DELETE' THEN
    SELECT username INTO from_name FROM public.card_profiles WHERE id = OLD.card_profile_id;
    INSERT INTO public.nfc_card_events
      (nfc_card_id, card_serial, card_code, action, from_profile_id, from_username, from_status, actor_id)
    VALUES
      (NULL, OLD.serial, OLD.card_url, 'deleted', OLD.card_profile_id, from_name, OLD.status, actor);
    RETURN OLD;
  END IF;

  IF NEW.card_profile_id IS DISTINCT FROM OLD.card_profile_id THEN
    SELECT username INTO from_name FROM public.card_profiles WHERE id = OLD.card_profile_id;
    SELECT username INTO to_name FROM public.card_profiles WHERE id = NEW.card_profile_id;
    INSERT INTO public.nfc_card_events
      (nfc_card_id, card_serial, card_code, action, from_profile_id, to_profile_id,
       from_username, to_username, from_status, to_status, actor_id)
    VALUES
      (NEW.id, NEW.serial, NEW.card_url,
       CASE
         WHEN OLD.card_profile_id IS NULL THEN 'assigned'
         WHEN NEW.card_profile_id IS NULL THEN 'unassigned'
         ELSE 'reassigned'
       END,
       OLD.card_profile_id, NEW.card_profile_id, from_name, to_name, OLD.status, NEW.status, actor);
  ELSIF NEW.status IS DISTINCT FROM OLD.status THEN
    INSERT INTO public.nfc_card_events
      (nfc_card_id, card_serial, card_code, action, from_status, to_status, actor_id)
    VALUES
      (NEW.id, NEW.serial, NEW.card_url, 'status_changed', OLD.status, NEW.status, actor);
  END IF;

  IF NEW.nickname IS DISTINCT FROM OLD.nickname OR NEW.location IS DISTINCT FROM OLD.location THEN
    INSERT INTO public.nfc_card_events
      (nfc_card_id, card_serial, card_code, action, details, actor_id)
    VALUES
      (NEW.id, NEW.serial, NEW.card_url, 'details_changed',
       jsonb_build_object(
         'nickname', NEW.nickname, 'location', NEW.location,
         'old_nickname', OLD.nickname, 'old_location', OLD.location
       ),
       actor);
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS nfc_cards_log_event ON public.nfc_cards;
CREATE TRIGGER nfc_cards_log_event
  AFTER INSERT OR UPDATE OR DELETE ON public.nfc_cards
  FOR EACH ROW EXECUTE FUNCTION public.log_nfc_card_event();

-- ----------------------------------------------- A5 public card lookup
-- Same narrow SECURITY DEFINER lookup as 057, plus status so a suspended or
-- retired card stops opening its profile.
DROP FUNCTION IF EXISTS public.resolve_nfc_card(TEXT);

CREATE OR REPLACE FUNCTION public.resolve_nfc_card(code TEXT)
RETURNS TABLE (
  nfc_card_id UUID,
  card_profile_id UUID,
  username TEXT,
  is_single_purpose BOOLEAN,
  redirect_kind TEXT,
  redirect_value TEXT,
  redirect_message TEXT,
  status TEXT
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT
    nc.id,
    nc.card_profile_id,
    cp.username,
    cp.is_single_purpose,
    (cp.buttons -> 0 ->> 'kind'),
    (cp.buttons -> 0 ->> 'value'),
    (cp.buttons -> 0 ->> 'message'),
    nc.status
  FROM public.nfc_cards nc
  LEFT JOIN public.card_profiles cp ON cp.id = nc.card_profile_id
  WHERE nc.card_url = code;
$$;

GRANT EXECUTE ON FUNCTION public.resolve_nfc_card(TEXT) TO anon, authenticated;

-- ------------------------------------------------- A6 per-card tap stats
-- SECURITY INVOKER: card_taps RLS still decides what the caller may count
-- (admins everything, owners their own).
CREATE OR REPLACE FUNCTION public.nfc_card_tap_stats(card_ids UUID[])
RETURNS TABLE (nfc_card_id UUID, taps BIGINT, first_tap TIMESTAMPTZ, last_tap TIMESTAMPTZ)
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = public
AS $$
  SELECT t.nfc_card_id, count(*), min(t.created_at), max(t.created_at)
  FROM public.card_taps t
  WHERE t.nfc_card_id = ANY (card_ids) AND t.event_type = 'view'
  GROUP BY t.nfc_card_id;
$$;

GRANT EXECUTE ON FUNCTION public.nfc_card_tap_stats(UUID[]) TO authenticated;

-- ============================================================ PART B
-- --------------------------------------------- B1 review card settings
ALTER TABLE public.card_profiles
  ADD COLUMN IF NOT EXISTS review_config JSONB;

-- --------------------------------------------- B2 review event types
ALTER TABLE public.card_taps DROP CONSTRAINT IF EXISTS card_taps_event_type_check;
ALTER TABLE public.card_taps
  ADD CONSTRAINT card_taps_event_type_check
  CHECK (event_type IN (
    'view',
    'contact_save',
    'share',
    'qr_open',
    'phone_click',
    'email_click',
    'whatsapp_click',
    'website_click',
    'social_click',
    'booking_click',
    'rating',
    'review_click',
    'feedback_open',
    'feedback_submit'
  ));

-- --------------------------------------------------- B3 feedback table
CREATE TABLE IF NOT EXISTS public.review_feedback (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  card_profile_id UUID NOT NULL REFERENCES public.card_profiles(id) ON DELETE CASCADE,
  nfc_card_id UUID REFERENCES public.nfc_cards(id) ON DELETE SET NULL,
  rating SMALLINT NOT NULL CHECK (rating BETWEEN 1 AND 5),
  category TEXT CHECK (category IS NULL OR char_length(category) <= 40),
  message TEXT CHECK (message IS NULL OR char_length(message) <= 2000),
  contact_name TEXT CHECK (contact_name IS NULL OR char_length(contact_name) <= 100),
  contact_phone TEXT CHECK (contact_phone IS NULL OR char_length(contact_phone) <= 40),
  contact_email TEXT CHECK (contact_email IS NULL OR char_length(contact_email) <= 200),
  source TEXT NOT NULL DEFAULT 'link' CHECK (source IN ('nfc', 'qr', 'link')),
  visitor_hash TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS review_feedback_profile_idx
  ON public.review_feedback(card_profile_id, created_at DESC);

ALTER TABLE public.review_feedback ENABLE ROW LEVEL SECURITY;

-- No INSERT policy on purpose: the only way in is submit_review_feedback(),
-- which checks the card itself rather than trusting ids from the browser.
DROP POLICY IF EXISTS "Owners can read feedback on their cards." ON public.review_feedback;
CREATE POLICY "Owners can read feedback on their cards."
  ON public.review_feedback FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.card_profiles cp
      WHERE cp.id = review_feedback.card_profile_id
        AND (cp.user_id = auth.uid() OR cp.org_owner_id = auth.uid())
    )
  );

DROP POLICY IF EXISTS "Admins can read all feedback." ON public.review_feedback;
CREATE POLICY "Admins can read all feedback."
  ON public.review_feedback FOR SELECT
  USING (public.is_admin());

CREATE OR REPLACE FUNCTION public.submit_review_feedback(
  p_username TEXT,
  p_code TEXT,
  p_rating INTEGER,
  p_category TEXT,
  p_message TEXT,
  p_name TEXT,
  p_phone TEXT,
  p_email TEXT,
  p_source TEXT,
  p_visitor_hash TEXT
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_profile UUID;
  v_card UUID;
  v_id UUID;
BEGIN
  SELECT id INTO v_profile
  FROM public.card_profiles
  WHERE username = lower(trim(p_username)) AND published = true;

  IF v_profile IS NULL THEN
    RAISE EXCEPTION 'card not found';
  END IF;

  -- A card code only counts if it is a live card pointing at this profile.
  IF p_code IS NOT NULL AND trim(p_code) <> '' THEN
    SELECT id INTO v_card
    FROM public.nfc_cards
    WHERE card_url = trim(p_code) AND card_profile_id = v_profile AND status = 'active';
  END IF;

  INSERT INTO public.review_feedback
    (card_profile_id, nfc_card_id, rating, category, message,
     contact_name, contact_phone, contact_email, source, visitor_hash)
  VALUES
    (v_profile, v_card, p_rating,
     NULLIF(trim(p_category), ''), NULLIF(trim(p_message), ''),
     NULLIF(trim(p_name), ''), NULLIF(trim(p_phone), ''), NULLIF(trim(p_email), ''),
     CASE WHEN p_source IN ('nfc', 'qr', 'link') THEN p_source ELSE 'link' END,
     p_visitor_hash)
  RETURNING id INTO v_id;

  RETURN v_id;
END;
$$;

REVOKE ALL ON FUNCTION public.submit_review_feedback(TEXT, TEXT, INTEGER, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT) FROM public;
GRANT EXECUTE ON FUNCTION public.submit_review_feedback(TEXT, TEXT, INTEGER, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT) TO anon, authenticated;
